buckets:
  stg_bucket:  cn-infra-lambda-artifacts-stg-ap
  prod_bucket: cn-infra-lambda-artifacts-prod-ap

lambdas:
  - function_name: cppv2_sqs_lambda_firehose_ap
    key: sqs-lambda-mapping
    handler: send_to_firehose

  - function_name: my-func-2
    key: lambdas
    handler: handler








